twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.project_dir%/templates/TwigBundle": Twig
        "%kernel.project_dir%/templates": ~
    form_themes:
        - 'form_theme.html.twig'
    globals:
        locales: [ru]
